#if defined _attdef_wc_callbacks
	#endinput
#endif
#define _attdef_wc_callbacks

#include "wc-callbacks\armourupdate.inc"
#include "wc-callbacks\damage.inc"
#include "wc-callbacks\damagedone.inc"
#include "wc-callbacks\finished.inc"
#include "wc-callbacks\healthupdate.inc"
//#include "wc-callbacks\finished.inc"
#include "wc-callbacks\invalid.inc"
#include "wc-callbacks\prepare.inc"
#include "wc-callbacks\rejected.inc"

