#if defined _attdef_wc_callbacks
	#endinput
#endif
#define _attdef_wc_callbacks

#include "wc-callbacks\OnArmourBarTextUpdate.inc"
#include "wc-callbacks\OnHealthBarTextUpdate.inc"
#include "wc-callbacks\OnInvalidWeaponDamage.inc"
#include "wc-callbacks\OnPlayerDamage.inc"
#include "wc-callbacks\OnPlayerDamageDone.inc"
#include "wc-callbacks\OnPlayerDeathFinished.inc"
#include "wc-callbacks\OnPlayerPrepareDeath.inc"
#include "wc-callbacks\OnRejectedHit.inc"
