#if !defined _attdef_header_incl
	#error "Module's header file include is not allowed here, include it in the correct section of the 'legacy/modules.inc' file."
#endif

#if defined _attdef_mod_duel
	#endinput
#endif
#define _attdef_mod_duel

/*
	Duel system
*/

#define DEFAULT_DUEL_ARENA_ID		-1
#define DEFAULT_DUEL_ARENA_X		-128.8940
#define DEFAULT_DUEL_ARENA_Y		1099.3207
#define DEFAULT_DUEL_ARENA_INTERIOR 0
